# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_education_api_key",
            field=models.CharField(
                blank=True,
                help_text="User's personal API key for the Data Education (Huwise) MCP integration.",
                max_length=255,
                null=True,
                verbose_name="Data Education API Key",
            ),
        ),
    ]
